BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[User] ADD [phoneNumber] NVARCHAR(1000),
[plan] NVARCHAR(1000) NOT NULL CONSTRAINT [User_plan_df] DEFAULT 'FREE',
[subscriptionStatus] NVARCHAR(1000) NOT NULL CONSTRAINT [User_subscriptionStatus_df] DEFAULT 'ACTIVE';

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
